title: Transport
description: A collection of APIs that are related to UK Transport
documentation_url: ""
services:
    - name: planned_road_works
      description: "Information on planned roadworks carried out on the Highways Agency network"
      documentation_url: ""
      schema_url: ""
      separator: comma
      dataset: highways_agency_planned_roadworks
      encoding: ascii
      table_settings:
        pk_name: reference_number
        index: road
        unique_fields: reference_number
        choice_fields:
      searchables:
        - name: road
          description: Find planned and historical roadworks by road (e.g. M1)
          query: select * from  planned_road_works where LOWER(road) = LOWER($1)
          fields:
            - road
    - name: anonymised_mot_test
      description: "Anonymised MOT results"
      documentation_url: ""
      schema_url: ""
      separator: pipe
      large_dataset: true
      encoding: ascii
      dataset: anonymised_mot_test
      table_settings:
        pk_name: testid
        index: make, model, testresult, year
        unique_fields: testid
        filter_fields:
          - make
          - postcoderegion
          - testclassid
          - fueltype
          - testresult
          - colour
          - year
        choice_fields:
          - make
          - postcoderegion
          - testclassid
          - fueltype
          - testresult
          - colour
          - year
      searchables:
        - name: year_and_make
          description: Find tests by year for a specific make of car
          query: select * from anonymised_mot_test where make = UPPER($1) AND date_part('year', testdate)::text = $2 limit 500;
          fields:
            - make
            - year

